import { Product } from "@/types/index";

// Sample product data array
const productData: Product[] = [
  {
    id: 1,
    productName: "Pro Plus 32 Inch TV",
    originalPrice: 500,
    discountedPrice: 475,
    discountPercentage: 5,
    productImage: "/assets/image/product/Pro Plus 32 Inch TV.png",
    rating: 4,
    reviews: 10,
    brandName: "Samsung",
    isNew: true,
    isBestSelling: true,
    favorites: 20,
    isFeatured: true,
    isOnDeal: true,
    isLatest: true,
    stock: 100,
    thumbnails: [
      "/assets/image/product/Pro Plus 32 Inch TV.png",
      "/assets/image/product/Pro Plus 32 Inch TV.png",
      "/assets/image/product/Pro Plus 32 Inch TV.png",
      "/assets/image/product/Pro Plus 32 Inch TV.png",
      "/assets/image/product/Pro Plus 32 Inch TV.png",
    ],
    discount: 5,
    colors: ["black", "blue"],
    types: ["M51", "M31"],
    description:
      "A powerful Samsung mobile with a 32-inch display and a high-end camera",
  },
  {
    id: 2,
    productName: "Samsung Galaxy S21",
    originalPrice: 800,
    discountedPrice: 750,
    discountPercentage: 6,
    productImage: "/assets/image/product/Samsung Galaxy S21.png",
    rating: 5,
    reviews: 18,
    reviewsMembers: [
      {
        reviewerName: "Ambrin",
        reviewDate: "21 Apr 2022 04:50:13 AM",
        rating: 1,
        comment: `I recently purchased a product from here, and I couldn't be happier with my online shopping experience. Their website was user-friendly, making it easy to find the perfect item.`,
        reviewerAvatar: "https://placehold.co/50x50",
        productImage: "https://placehold.co/50x50",
      },
    ],
    brandName: "Samsung",
    isNew: true,
    isBestSelling: true,
    favorites: 20,
    isFeatured: true,
    isOnDeal: true,
    isLatest: true,
    stock: 100,
    thumbnails: [
      "/assets/image/product/Samsung Galaxy S21.png",
      "/assets/image/product/Samsung Galaxy S21.png",
      "/assets/image/product/Samsung Galaxy S21.png",
      "/assets/image/product/Samsung Galaxy S21.png",
      "/assets/image/product/Samsung Galaxy S21.png",
    ],
    discount: 5,
    colors: ["black", "blue"],
    types: ["M51", "M31"],
    description:
      "A powerful Samsung mobile with a 32-inch display and a high-end camera",
  },
  {
    id: 3,
    productName: "Apple MacBook Pro",
    originalPrice: 1500,
    discountedPrice: 1400,
    discountPercentage: 7,
    productImage: "/assets/image/product/Apple-MacBook-Pro.png",
    rating: 4,
    reviews: 20,
    brandName: "Apple",
    isNew: true,
    isBestSelling: true,
    favorites: 20,
    isFeatured: true,
    isOnDeal: true,
    isLatest: true,
    stock: 100,
  },
  {
    id: 4,
    productName: "Latest Cool headphone with Bluetooth version 5.0",
    originalPrice: 1500,
    discountedPrice: 1400,
    discountPercentage: 7,
    productImage: "/assets/image/product/Latest Cool headphone.png",
    rating: 4,
    reviews: 18,
    brandName: "Apple",
    isNew: true,
    isBestSelling: true,
    favorites: 20,
    isFeatured: true,
    isOnDeal: true,
    isLatest: true,
  },
  {
    id: 5,
    productName: "Infinity pro v139",
    originalPrice: 1500,
    discountedPrice: 1400,
    discountPercentage: 7,
    productImage: "/assets/image/product/Infinity pro v139.png",
    rating: 4,
    reviews: 18,
    brandName: "Apple",
    isNew: true,
    isBestSelling: true,
    favorites: 20,
    isFeatured: true,
    isOnDeal: true,
  },
  {
    id: 6,
    productName: "Insta360 X3 Waterproof 360 Action Camera",
    originalPrice: 1500,
    discountedPrice: 1400,
    discountPercentage: 7,
    productImage:
      "/assets/image/product/Insta360 X3 Waterproof 360 Action Camera.png",
    rating: 4,
    reviews: 15,
    brandName: "Apple",
    isNew: true,
    isBestSelling: true,
    favorites: 20,
    isFeatured: true,
    isOnDeal: true,
    isLatest: true,
  },
];
export default productData;
